package dabells;
import net.minecraft.block.Block;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.MinecraftForge;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.GameRegistry;
import dabells.blocks.BlockBell;
import dabells.tileentities.TEBellSilver;

@Mod(modid = Infofile.ID, name = Infofile.NAME, version = Infofile.VERS)

public class DaBells
{
		
//Blocks
	//Tier 0 (Decorative) Bell Blocks
		public static final Block BellSilver = new BlockBell("BellSilver");

	@Instance(Infofile.NAME)
	public static DaBells instance;
	
	@SidedProxy(clientSide=Infofile.CLIENTPROXY + "ClientProxy", serverSide=Infofile.COMMONPROXY + "CommonProxy")
	public static CommonProxy proxy;
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{
		proxy.registerRenderers();
		
		proxy.config(event);
		
		ModMetadata mod = event.getModMetadata(); 
		mod.autogenerated = false;
		mod.authorList.add(Infofile.AUTH);
		mod.credits = Infofile.CRED;
		mod.description = Infofile.DESCRIP;
		mod.logoFile = Infofile.LOGO;
		mod.modId = Infofile.ID;
		mod.name = Infofile.NAME;
		mod.parent = Infofile.PARENT;
		mod.screenshots = Infofile.SCREEN;
		mod.updateUrl = Infofile.UDURL;
		mod.url = Infofile.URL;
		mod.version = Infofile.VERS;
		
//Tier 0 Bell Blocks
     	GameRegistry.registerBlock(BellSilver, "BellSilver");

//TileEntities
      	if (CommonProxy.resolution == 0) 
      	{
     	GameRegistry.registerTileEntity(TEBellSilver.class, "TEBellSilver");
      	}
//Blocks

//OreDictionary

//Bell Recipes
	//Blocks
      	//ItemStacks

     //Tier 0 (Decorative) Bell Blocks
     	GameRegistry.addRecipe(new ItemStack(BellSilver, 1), new Object[]
				{"TYT", "YXY", "YYY", 'T', Items.stick, 'Y', Items.iron_ingot, 'X', Items.string});


	//Item

//Smelting (only for Tier 0 Bells)		
		//ItemStacks for Bell Breakdown		
		ItemStack ingiron6 = new ItemStack(Items.iron_ingot, 6);
		ItemStack quartz6 = new ItemStack(Items.quartz, 6);
		ItemStack redstone6 = new ItemStack(Items.redstone, 6);
		ItemStack lapis6 = new ItemStack(Items.dye, 6, 4);
		ItemStack nuggold46 = new ItemStack(Items.gold_nugget, 46);
		ItemStack diamond6 = new ItemStack(Items.diamond, 6);
		ItemStack enderpearl6 = new ItemStack(Items.ender_pearl, 6);
		ItemStack emerald6 = new ItemStack(Items.emerald, 6);
		//Bell Smelting		
		GameRegistry.addSmelting(BellSilver, ingiron6, 0.0F);
		
		MinecraftForge.EVENT_BUS.register(new EventHook());
	}
	
	@EventHandler
	public void load(FMLInitializationEvent event)
	{proxy.registerRenderers();}
	
	@EventHandler
	public void postInit(FMLPostInitializationEvent event) 
	{
		FMLCommonHandler.instance().bus().register(new onLogOn());
	}
}
