//Date: 15/01/14 01:11:50
//Template version 1.1
//Java generated by Techne
//Keep in mind that you still need to fill in some blanks
//- ZeuX

package dabells.blocks;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class BellModel extends ModelBase
{
//fields
 ModelRenderer bell;
 ModelRenderer fixture;


    public BellModel()
    {
        textureWidth = 32;
        textureHeight = 32;

        bell = new ModelRenderer(this, 0, 0);
        bell.addBox(-3.0f, -6.0f, -3.0f, 6, 7, 6);
        bell.setRotationPoint(0.0f, 12.0f - 4f, 0.0f);
        bell.setTextureSize(32, 32);
        bell.mirror = true;

        fixture = new ModelRenderer(this, 0, 13);
        fixture.addBox(4.0f, 4.0f, 4.0f, 8, 2, 8);
        fixture.setRotationPoint(-8.0f, -12.0f + 16f, -8.0f);
        fixture.setTextureSize(32, 32);
        fixture.mirror = true;
    }



    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);

        // Render the bell
        bell.rotateAngleX = f; // replace 'f' with the desired rotateAngleX for the bell
        bell.rotateAngleZ = f1; // replace 'f1' with the desired rotateAngleZ for the bell
        bell.render(0.0625f);
    }


private void setRotation(ModelRenderer model, float x, float y, float z)
{
 model.rotateAngleX = x;
 model.rotateAngleY = y;
 model.rotateAngleZ = z;
}

public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
{
 super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
}

public void renderModel(float f)
{
	 bell.render(f);
    fixture.render(f);

}

}
